name: 'Test: Azure Static Web App deployment'
on:
  push:
    branches:
      - test
      - main
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          REACT_APP_auth_azuread_client_auth_clientId: ${{ secrets.TEST_REACT_APP_auth_azuread_client_auth_clientId }}
          REACT_APP_auth_azuread_client_auth_authority: ${{ secrets.TEST_REACT_APP_auth_azuread_client_auth_authority }}
          REACT_APP_auth_azuread_client_auth_redirectUri: ${{ secrets.TEST_REACT_APP_auth_azuread_client_auth_redirectUri }}
          REACT_APP_auth_azuread_client_auth_postLogoutRedirectUri: ${{ secrets.TEST_REACT_APP_auth_azuread_client_auth_postLogoutRedirectUri }}
          REACT_APP_auth_azuread_login_scopes: ${{ secrets.TEST_REACT_APP_auth_azuread_login_scopes }}
          REACT_APP_VTFK_VIKARAPI_BASEURL: ${{ secrets.REACT_APP_VTFK_VIKARAPI_BASEURL }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_WATER_0AF444F03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional